version: "3.9"

services:
  web:
    image: nginx
    container_name: webserver-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - php

  php:
    container_name: php-dev-8.1
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./public:/var/www/html
    environment:
      - XDEBUG_PORT=9003
      - XDEBUG_HOST=host.docker.internal2
    command: php-fpm --nodaemonize
  
  db:
    image: mysql
    container_name: db-mysql-dev
    restart: 'no'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=sail

networks:
  webnetwork:
    driver: bridge