version: "3.9"

services:
  web:
    image: nginx:1.25.1
    container_name: webserver-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    ports:
      - "${APP_PORT}:${NGINX_PORT}"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    depends_on:
      - php

  php:
    container_name: php-dev-8.1
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./public:/var/www/html
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - XDEBUG_PORT=${XDEBUG_PORT}
      - XDEBUG_HOST=${XDEBUG_HOST}
    command: php-fpm --nodaemonize

  db:
    image: mysql:8.0
    container_name: db-mysql-dev
    restart: 'no'
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

networks:
  webnetwork:
    driver: bridge
